services:
  license-server:
    build:
      context: ./license_portal
    links:
      - mariadb
    volumes:
      - ./license_portal:/app
    ports:
      - '8080:8080'
    working_dir: /app
    command: bash -c "python manage.py migrate && python manage.py createsuperuser --no-input || true && python manage.py runserver 0.0.0.0:8080"
    environment:
      - DJANGO_SUPERUSER_PASSWORD=password
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=mail@mail.com
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: licenses
      MYSQL_USER: licenses
      MYSQL_PASSWORD: licenses
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "mariadb", "--silent"]
      timeout: 10s
      retries: 6

  redis:
    image: redis
    ports:
      - '6379:6379'

  celery-worker:
    build:
      context: ./license_portal
    volumes:
      - ./license_portal:/app
    working_dir: /app
    command: bash -c "celery -A licenses worker --loglevel=info"
    links:
      - mariadb
      - redis
    depends_on:
      - mariadb
      - redis